INSERT INTO HEKIM VALUES ('SENA','SAHIN','a@gmail.com','Qwert123','1');
INSERT INTO HEKIM VALUES ('MUSTAFA','ILDEMIR','b@gmail.com','Qwert123','2');
INSERT INTO HEKIM VALUES ('EREN','DEMIRTAS','c@gmail.com','Qwert123','3');

INSERT INTO STAJER VALUES ('HANEFI','BALCI','d@gmail.com','Qwert123','4');
INSERT INTO STAJER VALUES ('KADIR','KARA','e@gmail.com','Qwert123','5');
INSERT INTO STAJER VALUES ('TALHA','CETIN','f@gmail.com','Qwert123','6');

INSERT INTO BAGLIDIR VALUES('1','6');
INSERT INTO BAGLIDIR VALUES('1','4');
INSERT INTO BAGLIDIR VALUES('2','4');
INSERT INTO BAGLIDIR VALUES('2','5');
INSERT INTO BAGLIDIR VALUES('3','5');

INSERT INTO SAHIP VALUES('123456789111','CAGRI','DALDAL','g@gmail.com','Qwert123');
INSERT INTO SAHIP VALUES('123456789112','EYLUL','OZGUN','h@gmail.com','Qwert123');

INSERT INTO HAYVAN VALUES(1,'123456789111','TEKIR','KEDI',3);
INSERT INTO HAYVAN VALUES(2,'123456789112','YUMAK','TAVSAN',1);
